name: build.yml
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup PHP Action
        uses: shivammathur/setup-php@2.27.1
        with:
          php-version: '8.2'
          tools: php-cs-fixer, phpstan
      - name: Install Composer and Dependencies
        run: composer install
      - name: Run tests
        run: ./vendor/bin/phpunit
      - name: Phpstan
        run: phpstan analyse src tests --level max
      - name: cs fixer
        run: php-cs-fixer --dry-run
